"""部分空間正則化PCAと先行シグナル予測λ。"""

from .model import LeadingLambdaClassifier, Prediction
from .signals import build_leading_features, build_training_set
from .relative_strength_feature import (
    RELATIVE_STRENGTH_FEATURE_VERSION,
    RELATIVE_STRENGTH_PERIODS,
    build_relative_strength_features,
    calculate_relative_strength_index,
)
from .recursive_self_improvement import (
    RECURSIVE_SELF_IMPROVEMENT_VERSION,
    MarketFutureEvaluation,
    MarketFrozenTrial,
    MarketPromotionReport,
    MarketRecursiveImprovementGate,
    MarketRsiCandidate,
    SequentialEvidence,
    candidate_manifest_digest,
    freeze_candidate,
    freeze_trial,
    freeze_promotion_report,
    parameter_manifest_digest,
    sequential_loss_improvement_test,
    trial_manifest_digest,
    validate_successor,
)
from .error_classification import (
    ERROR_CATEGORIES,
    EXTRACTION_MISS,
    FINAL_EXCLUSION,
    MARKET_NOISE,
    MISSING_INPUT,
    MIN_RATIONALE_SESSIONS,
    OVERESTIMATION,
    CandidateRationale,
    classify_extreme_selection,
    classify_target_settlement,
    freeze_candidate_rationale,
    rationale_manifest_digest,
    summarize_error_classification,
)
from .validation import WalkForwardResult, walk_forward_validate
from .collector import DailyMarketCollector, MarketDataset, DEFAULT_UNIVERSE
from .paper_backtest import PaperBacktestResult, run_paper_backtest
from .paper_pca_sub import PaperPcaSubModel, PaperSignal

__all__ = [
    "LeadingLambdaClassifier",
    "Prediction",
    "WalkForwardResult",
    "build_leading_features",
    "build_training_set",
    "RELATIVE_STRENGTH_FEATURE_VERSION",
    "RELATIVE_STRENGTH_PERIODS",
    "RECURSIVE_SELF_IMPROVEMENT_VERSION",
    "MarketFutureEvaluation",
    "MarketFrozenTrial",
    "MarketPromotionReport",
    "MarketRecursiveImprovementGate",
    "MarketRsiCandidate",
    "SequentialEvidence",
    "candidate_manifest_digest",
    "build_relative_strength_features",
    "calculate_relative_strength_index",
    "freeze_candidate",
    "freeze_trial",
    "freeze_promotion_report",
    "parameter_manifest_digest",
    "sequential_loss_improvement_test",
    "trial_manifest_digest",
    "validate_successor",
    "ERROR_CATEGORIES",
    "EXTRACTION_MISS",
    "FINAL_EXCLUSION",
    "MARKET_NOISE",
    "MISSING_INPUT",
    "MIN_RATIONALE_SESSIONS",
    "OVERESTIMATION",
    "CandidateRationale",
    "classify_extreme_selection",
    "classify_target_settlement",
    "freeze_candidate_rationale",
    "rationale_manifest_digest",
    "summarize_error_classification",
    "walk_forward_validate",
    "DailyMarketCollector",
    "MarketDataset",
    "DEFAULT_UNIVERSE",
    "PaperPcaSubModel",
    "PaperSignal",
    "PaperBacktestResult",
    "run_paper_backtest",
]
